Azure/api-management-self-hosted-gateway

charts/azure-api-management-gateway/.helmignore
charts/azure-api-management-gateway/Chart.yaml
charts/azure-api-management-gateway/README.md
charts/azure-api-management-gateway/templates/NOTES.txt
charts/azure-api-management-gateway/templates/_helpers.tpl
charts/azure-api-management-gateway/templates/configmap.yaml
charts/azure-api-management-gateway/templates/deployment.yaml
charts/azure-api-management-gateway/templates/ingress.yaml
charts/azure-api-management-gateway/templates/secret.yaml
charts/azure-api-management-gateway/templates/service.yaml
charts/azure-api-management-gateway/templates/tests/test-connection.yaml
charts/azure-api-management-gateway/values.yaml

Donate 'Azure API Management Gateway' Helm chart from https://github.com/tomkerkhove/azure-api-management-gateway-helm to official repo.

Donate 'Azure API Management Gateway' Helm chart

---

helm-charts/azure-api-management-gateway/README.md

Remove reference to Promitor which slipped in due to copy paste from my side

Remove reference to Promitor

---

.github/workflows/lint-helm-charts.yml

Lint Helm Chart in every PR against Helm 3.x

Lint Helm Chart in every PR

---

helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/values.yaml

Allow users to use private images built on top of the official image

---

.github/CODEOWNERS

Provide CODEOWNERS to automatically assign reviewers

Provide CODEOWNERS

---

helm-charts/azure-api-management-gateway/Chart.yaml

chore: Change app version to 1.2.5 & chart maintenance

---

helm-charts/azure-api-management-gateway/Chart.yaml
helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/service.yaml
helm-charts/azure-api-management-gateway/values.yaml

feat: Provide port forwarding for HTTP & HTTPS

---

.github/workflows/ci-helm-chart.yml

test: Improve deployment of gateway in CI

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/configmap.yaml
helm-charts/azure-api-management-gateway/values.yaml

feat: Provide capability to emit metrics to Azure Monitor

---

.github/workflows/ci-helm-chart.yml

chore: Show logs of gateway in CI

---

helm-charts/azure-api-management-gateway/templates/deployment.yaml

Provide metadata around deployment mechanism & runtime to improve supportability.

feat: Provide metadata around deployment mechanism & runtime

---

README.md
gateway-license.md

Provide guidance around licensing for self-hosted gateway

chore: Provide guidance around licensing for self-hosted gateway

---

.github/workflows/ci-helm-chart.yml

chore: Run CI against Kubernetes v1.17 -> v1.24

---

helm-charts/azure-api-management-gateway/templates/configmap.yaml

Enforce specifying Configuration API URL

feat: Enforce specifying Configuration API URL

---

.github/workflows/ci-helm-chart.yml

Use secrets from Azure Key Vault with OIDC authentication so that external PRs can use valid credentials to run gateway with.

ci: Use secrets from Azure Key Vault with OIDC authentication

---

helm-charts/azure-api-management-gateway/Chart.yaml

https://github.com/Azure/api-management-self-hosted-gateway/releases/tag/Container-v2.1.5

feat: Use SHGW v2.1.5

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/ingress-stable.yaml

This pull-request implements a solution for #177
The changes have been tested locally

feat: Add support for `ingressClassName` in ingress

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/ingress-stable.yaml
helm-charts/azure-api-management-gateway/values.yaml

This is a PR for #182 
I think a cleaner solution would need a breaking change of the helm chart

feat: add option to access https port of gateway over ingress

---

.github/workflows/ci-helm-chart.yml
helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/configmap.yaml
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/templates/secret.yaml
helm-charts/azure-api-management-gateway/values.yaml

Relates to https://github.com/Azure/api-management-self-hosted-gateway/issues/213

feat: Provide capability to use Azure AD authentication

---

.github/workflows/ci-main.yml
.github/workflows/ci-pr.yml

Relates to https://github.com/Azure/api-management-self-hosted-gateway/issues/213
Depends on https://github.com/Azure/api-management-self-hosted-gateway/pull/212

ci: Provide dedicated CI for main and integrate Azure AD authentication

---

.github/ISSUE_TEMPLATE/1_feature_request.yml

Add @ferantoMSFT as assignee for feature requests

chore: Add @ferantoMSFT as assignee for feature requests

---

helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/values.yaml

Add option to remove replicaCount in case of custom scaling see:
https://github.com/Azure/api-management-self-hosted-gateway/issues/234
or
https://github.com/Azure/api-management-self-hosted-gateway/discussions/235

feat: Add option to remove replicaCount property (in case of custom scaling)

---

helm-charts/azure-api-management-gateway/templates/configmap.yaml
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/templates/ingress-controller.yaml
helm-charts/azure-api-management-gateway/templates/persistent-volume-claim.yaml
helm-charts/azure-api-management-gateway/templates/pod-disruption-budget.yaml
helm-charts/azure-api-management-gateway/templates/secret.yaml
helm-charts/azure-api-management-gateway/templates/service-instance-discovery.yaml
helm-charts/azure-api-management-gateway/templates/service.yaml
helm-charts/azure-api-management-gateway/templates/tests/test-connection.yaml

Fixes https://github.com/Azure/api-management-self-hosted-gateway/issues/295

fix: Respect Helm installation namespace

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/_helpers.tpl
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/values.yaml

Add option to add custom labels to deployed resources

feat: add common labels
