README.md
helm-charts/azure-api-management-gateway/README.md

Provide docs on Helm installation to make it easier to get people started.
Renamed the sample repo (`apim-gateway`) to `azure-apim-gateway` in case they have other repos configured already to clarify that it's Azures APIM Gateway.

Provide docs on Helm installation

---

helm-charts/azure-api-management-gateway/templates/tests/test-connection.yaml

For clusters with multiple operating systems it is necessary to ensure that all pods contain OS scheduling requirements so that they are scheduled on a compatible node. This is covered in all templates in the chart except for the test pod which this PR adds support for.

Add nodeSelector to test pod

---

helm-charts/azure-api-management-gateway/Chart.yaml
helm-charts/azure-api-management-gateway/templates/ingress.yaml

The extensions/v1beta1 api for ingress is being removed in 1.16
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
The new api has been available since kubernetes version 1.14 so we can
simply have a conditional on it.
Signed-off-by: Kristinn Björgvin Árdal <kristinnardalsecondary@gmail.com>

Change ingress apiVersion for kubernetes versions 1.14 and higher.

---

.github/workflows/lint-helm-charts.yml
helm-charts/azure-api-management-gateway/values.yaml

```shell
❯ helm lint .\helm-charts\azure-api-management-gateway\
==> Linting .\helm-charts\azure-api-management-gateway\
[ERROR] templates/: template: azure-api-management-gateway/templates/secret.yaml:12:44: executing "azure-api-management-gateway/templates/secret.yaml" at <b64enc>: invalid value; expected string
Error: 1 chart(s) linted, 1 chart(s) failed
```
```shell
❯ helm lint .\helm-charts\azure-api-management-gateway\ --set gateway.endpoint=abc --set gateway.authKey=XYZ
==> Linting .\helm-charts\azure-api-management-gateway\
1 chart(s) linted, 0 chart(s) failed
```

Enforce users to specify gateway configuration

---

helm-charts/azure-api-management-gateway/Chart.yaml
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/values.yaml

Use app version as image tag & update Helm chart spec.
This allows us to have a more discoverable Helm chart on Artifact Hub.
**🔔 This will change the way the gateway is released**
Every new version of the gateway container, should bump the app version. This allows operators to understand what image is running in the cluster instead of always using `latest` which is an anti-pattern ([learn more](https://codefresh.io/kubernetes-tutorial/kubernetes-antipatterns-1/).

Use app version as image tag & update Helm chart spec

---

helm-charts/azure-api-management-gateway/templates/service.yaml
helm-charts/azure-api-management-gateway/values.yaml

Closes #22
```
❯ helm template .\helm-charts\azure-api-management-gateway\
<redacted>
---
apiVersion: v1
kind: Service
metadata:
name: RELEASE-NAME-azure-api-management-gateway
labels:
app.kubernetes.io/name: azure-api-management-gateway
helm.sh/chart: azure-api-management-gateway-0.3.0
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/managed-by: Helm
spec:
type: ClusterIP
```
```diff
❯ helm template .\helm-charts\azure-api-management-gateway\ --values .\lint-values.yml
<redacted>
---
apiVersion: v1
kind: Service
metadata:
name: RELEASE-NAME-azure-api-management-gateway
labels:
app.kubernetes.io/name: azure-api-management-gateway
helm.sh/chart: azure-api-management-gateway-0.3.0
app.kubernetes.io/instance: RELEASE-NAME …
```

Provide capability to specify annotations to the service

---

.github/workflows/ci-helm-chart.yml

We will now automatically deploy the Helm chart on the last 6 Kubernetes versions (v1.22 -> v1.17).

test: Automatically run deploy against multiple Kubernetes versions

---

.github/workflows/ci-helm-chart.yml
README.md
helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/configmap.yaml
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/templates/secret.yaml
helm-charts/azure-api-management-gateway/values.yaml

As we are going to ship a new major version due to #46, it's the perfect timing to revise our current Helm configuration setup and make it more future-proof.
Breaking changes:
- `gateway.endpoint` ➡️ `gateway.configuration.uri` 
- `gateway.authKey` ➡️ `gateway.auth.key` 
- `dapr.appId` ➡️ `dapr.app.id`

chore: Make configuration more future-proof

---

helm-charts/azure-api-management-gateway/Chart.yaml

I would like the APIM chart to support pre-release/non-vanilla versions of Kubernetes, for instance v1.21.5-gke.1302 or v1.18.9-eks-d1db3c. This fix should add support for these Kubernetes versions.

feat: Allow support for deploying on Kubernetes clusters running pre-release versions

---

.github/workflows/ci-helm-chart.yml

Use Kind v1.3.0 for Kubernetes v1.24 validation to coop with breaking changes.
> You must use kind v0.13.0+ with Kubernetes v1.24.0+ images, and if you built your own Kubernetes v1.24.0+ image with a previous kind version you will need to re-built when switching to kind v0.13.0+.
https://github.com/kubernetes-sigs/kind/releases/tag/v0.13.0

fix: Use Kind v1.3.0 for Kubernetes v1.24 validation

---

helm-charts/azure-api-management-gateway/values.yaml

Use 3 replicas of gateway by default for HA purposes to ensure that there is no single-point-of-failure

feat: Use 3 replicas of gateway by default for HA purposes

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/values.yaml

Added an option to define custom annotation for the gateway deployment.
While testing I found out that the current implementation for dapr handling is broken. Following error occurs:
```
Helm upgrade failed: YAML parse error on azure-api-management-gateway/templates/deployment.yaml: error converting YAML to JSON: yaml: line 24: mapping ││  values are not allowed in this context
```
This bug is also fixed with this PR.

feat: add option to set custom annotation for deployment

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/values.yaml

The configuration URL is not added to the public DNS in case the APIM is in VNET. 
This way you can specify given configuration URL and it's IP directly to the APIM deployment.

feat: Provide support for configuring hostAliases

---

helm-charts/azure-api-management-gateway/templates/deployment.yaml

The current configuration that uses ```{{- with .Values.affinity }}``` results in Helm failing to generate the template when ```.Values.affinity``` is set.
This is caused because with sets the context to ```.Values.affinity```, which makes the values of ```.Capablilities``` and ```.Release``` nil, resulting in the following error:
```
Error: template: azure-api-management-gateway/templates/deployment.yaml:131:44: executing "azure-api-management-gateway/templates/deployment.yaml" at <.Capabilities.KubeVersion.Version>: nil pointer evaluating interface {}.KubeVersion
```
Changing the ```with``` to an ```if``` statement and expanding ```toYaml .``` into ```toYaml .Values.affinity``` fixes this error.

fix: Changed deployment.yaml to use if instead of with statement

---

.github/ISSUE_TEMPLATE/2_bug_report.yml
helm-charts/azure-api-management-gateway/templates/deployment.yaml
test-config.yml

Remove legacy Kubernetes features as we don't allow these Kubernetes versions anymore and follow-up on #188 as the main problem was the version check.
Also added affinity to the test configuration.

chore: Remove legacy Kubernetes features

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/service.yaml

Added support for the `loadBalancerIP`-field in the service to allow the use of preprovisioned IP's when running on supported cloud providers.

feat: Add support for loadBalancerIP in service configuration (#198

---

helm-charts/azure-api-management-gateway/templates/deployment.yaml

Minor bug in my [previous commit](https://github.com/Azure/api-management-self-hosted-gateway/pull/263) where the `replicaCount: 0` was considered as an `null` and was reduced.
The correct behavior should be:
replicaCount: 1 -> replicas: 1
replicaCount: 0 -> replicas: 0
replicaCount:  -> reduced
replicaCount: NULL -> reduced

fix: 0 replica count should not be reduced

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/service.yaml
helm-charts/azure-api-management-gateway/values.yaml

add option allocateLoadBalancerNodePorts
see #279

feat: allocateLoadBalancerNodePorts option

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/deployment.yaml
helm-charts/azure-api-management-gateway/values.yaml

feat: add startup probe

---

helm-charts/azure-api-management-gateway/README.md
helm-charts/azure-api-management-gateway/templates/deployment.yaml

add option to run gateway with a custom priorityClass to make it easier to run the gateway with higher priority than other pods in the cluster. See [kubernetes docs](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) for more details.

feat: add option to set priority class
